import type { ContentItem } from '../types';

// Mock data for demonstration
export const mockContentItems: ContentItem[] = [
    // Incoming RSS
    {
        id: '1',
        originalTitle: 'OpenAI releases new GPT-5 distinct capabilities',
        originalDesc: 'OpenAI has announced the release of GPT-5 with groundbreaking new features...',
        originalUrl: 'https://techcrunch.com/gpt-5',
        status: 'incoming',
        platform: 'both',
        selectedVar: 0,
        createdAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
        updatedAt: new Date().toISOString(),
        source: { id: '1', name: 'TechCrunch', url: 'https://techcrunch.com/feed', isActive: true },
        category: { id: '1', name: 'Tech', slug: 'tech', color: '#3B82F6', isActive: true },
    },
    {
        id: '2',
        originalTitle: 'Minimalist UI trends for 2024 SaaS products',
        originalDesc: 'Discover the latest UI design trends shaping SaaS products...',
        originalUrl: 'https://dribbble.com/minimalist',
        status: 'incoming',
        platform: 'both',
        selectedVar: 0,
        createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
        updatedAt: new Date().toISOString(),
        source: { id: '2', name: 'Dribbble Blog', url: 'https://dribbble.com/feed', isActive: true },
        category: { id: '2', name: 'Design', slug: 'design', color: '#A855F7', isActive: true },
    },

    // AI Generated
    {
        id: '3',
        originalTitle: 'Why AI Automation is the Future of Content Strategy',
        originalUrl: 'https://example.com/ai-future',
        headline: 'Why AI Automation is the Future of Content Strategy',
        subheadline: 'Transform your workflow with intelligent automation',
        igCaption: '🤖 AI is revolutionizing content strategy!\n\nDiscover how automation can:\n• Save 10+ hours weekly\n• Boost engagement by 3x\n• Scale your content effortlessly\n\nLink in bio! 👆\n\n#AI #Automation #ContentStrategy #Marketing #Tech',
        fbCaption: 'AI is changing the game for content creators. Learn how automation can transform your workflow and boost your results.',
        aiConfidence: 0.98,
        status: 'ai_generated',
        platform: 'both',
        selectedVar: 0,
        createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
        updatedAt: new Date().toISOString(),
        category: { id: '1', name: 'Tech', slug: 'tech', color: '#3B82F6', isActive: true },
    },
    {
        id: '4',
        originalTitle: 'Top 5 Productivity Hacks for Remote Teams',
        originalUrl: 'https://example.com/productivity',
        headline: 'Top 5 Productivity Hacks for Remote Teams',
        igCaption: 'Remote work is here to stay. Discover how top performing teams manage their time effectively...',
        aiConfidence: 0.75,
        status: 'ai_generated',
        platform: 'both',
        selectedVar: 0,
        createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
        updatedAt: new Date().toISOString(),
        category: { id: '1', name: 'Tech', slug: 'tech', color: '#3B82F6', isActive: true },
    },

    // Waiting Approval
    {
        id: '5',
        originalTitle: '5 Ways to Automate Your Morning',
        originalUrl: 'https://example.com/morning',
        headline: '5 Ways to Automate Your Morning',
        subheadline: 'Start your day smarter, not harder',
        igCaption: 'Waking up is hard, but your workflow doesn\'t have to be. ☕\n\nDiscover how AI can streamline your morning routine before you even finish your first cup.\n\nLink in bio for the full guide! 👇\n\n#Automation #AI #Productivity #MorningRoutine #TechTips',
        fbCaption: 'Mornings made easy with AI. Check out our guide to automating your daily routine and starting each day with less stress.',
        aiConfidence: 0.92,
        status: 'waiting_approval',
        platform: 'both',
        selectedVar: 0,
        createdAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
        updatedAt: new Date().toISOString(),
        category: { id: '1', name: 'Tech', slug: 'tech', color: '#3B82F6', isActive: true },
    },
    {
        id: '6',
        originalTitle: 'Q3 Financial Results Breakdown',
        originalUrl: 'https://example.com/q3',
        headline: 'Q3 Financial Results Breakdown',
        igCaption: 'Breaking down Q3 results...',
        status: 'waiting_approval',
        platform: 'both',
        selectedVar: 0,
        createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date().toISOString(),
        category: { id: '3', name: 'Finance', slug: 'finance', color: '#22C55E', isActive: true },
    },

    // Approved
    {
        id: '7',
        originalTitle: 'Sustainable Energy Growth',
        originalUrl: 'https://example.com/energy',
        headline: 'Sustainable Energy Growth',
        igCaption: 'The future of energy is green...',
        status: 'approved',
        platform: 'both',
        selectedVar: 0,
        scheduledAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
        createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date().toISOString(),
        category: { id: '1', name: 'Tech', slug: 'tech', color: '#3B82F6', isActive: true },
    },
];
