import { useState } from 'react';
import type { ContentItem } from '../../types';

interface DetailPanelProps {
    item: ContentItem;
    onClose?: () => void;
    onApprove?: (item: ContentItem) => void;
    onReject?: (item: ContentItem) => void;
    onEdit?: (item: ContentItem) => void;
}

type PlatformTab = 'instagram' | 'facebook';

const statusLabels: Record<string, { label: string; className: string }> = {
    incoming: {
        label: 'Incoming',
        className: 'bg-blue-100 text-blue-600 dark:bg-blue-900/30 dark:text-blue-400'
    },
    ai_generated: {
        label: 'AI Generated',
        className: 'bg-primary/20 text-primary-content dark:text-primary'
    },
    waiting_approval: {
        label: 'Waiting Approval',
        className: 'bg-orange-100 text-orange-600 dark:bg-orange-900/30 dark:text-orange-400'
    },
    approved: {
        label: 'Approved',
        className: 'bg-green-100 text-green-600 dark:bg-green-900/30 dark:text-green-400'
    },
    scheduled: {
        label: 'Scheduled',
        className: 'bg-gray-100 text-gray-600 dark:bg-gray-900/30 dark:text-gray-400'
    },
};

export function DetailPanel({
    item,
    onClose,
    onApprove,
    onReject,
    onEdit
}: DetailPanelProps) {
    const [activeTab, setActiveTab] = useState<PlatformTab>('instagram');
    const status = statusLabels[item.status] || statusLabels.incoming;

    const caption = activeTab === 'instagram' ? item.igCaption : item.fbCaption;
    const showActions = item.status === 'waiting_approval';

    return (
        <aside className="w-[400px] flex-shrink-0 bg-surface-light dark:bg-surface-dark border-l border-border-light dark:border-border-dark flex flex-col h-full shadow-xl z-20 overflow-y-auto custom-scrollbar">
            {/* Panel Header */}
            <div className="flex items-center justify-between p-6 border-b border-border-light dark:border-border-dark">
                <div className="flex items-center gap-2">
                    <span className={`text-xs font-bold px-2 py-1 rounded-md uppercase tracking-wider ${status.className}`}>
                        {status.label}
                    </span>
                    <span className="text-xs text-text-muted">Draft #{item.id.slice(0, 4)}</span>
                </div>
                <button
                    onClick={onClose}
                    className="text-text-muted hover:text-text-main dark:hover:text-white"
                >
                    <span className="material-symbols-outlined">close</span>
                </button>
            </div>

            <div className="p-6 flex-1">
                {/* Source Info */}
                <div className="flex items-center justify-between mb-6">
                    <div className="flex items-center gap-3">
                        <div className="size-8 rounded-full bg-primary/20 flex items-center justify-center text-xl">
                            ☕
                        </div>
                        <div className="flex flex-col">
                            <span className="text-sm font-bold text-text-main dark:text-white">
                                {item.source?.name || 'Original Idea'}
                            </span>
                            <span className="text-xs text-text-muted">
                                Generated by AI • {new Date(item.createdAt).toLocaleTimeString()}
                            </span>
                        </div>
                    </div>
                    {item.originalUrl && (
                        <a
                            href={item.originalUrl}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="flex items-center gap-1 text-xs text-primary hover:underline"
                        >
                            <span className="material-symbols-outlined text-[14px]">open_in_new</span>
                            Original
                        </a>
                    )}
                </div>

                {/* Content Preview */}
                <div className="mb-6">
                    <label className="block text-xs font-bold text-text-muted uppercase tracking-wider mb-3">
                        Platform Preview
                    </label>

                    {/* Tabs */}
                    <div className="flex border-b border-border-light dark:border-border-dark mb-4">
                        <button
                            onClick={() => setActiveTab('instagram')}
                            className={`px-4 py-2 text-sm font-medium transition-colors ${activeTab === 'instagram'
                                ? 'border-b-2 border-primary text-primary'
                                : 'text-text-muted hover:text-text-main dark:hover:text-white'
                                }`}
                        >
                            Instagram
                        </button>
                        <button
                            onClick={() => setActiveTab('facebook')}
                            className={`px-4 py-2 text-sm font-medium transition-colors ${activeTab === 'facebook'
                                ? 'border-b-2 border-primary text-primary'
                                : 'text-text-muted hover:text-text-main dark:hover:text-white'
                                }`}
                        >
                            Facebook
                        </button>
                    </div>

                    {/* Mockup */}
                    <div className="border border-border-light dark:border-border-dark rounded-xl overflow-hidden bg-white dark:bg-[#1a1f14]">
                        {/* Image */}
                        <div
                            className="aspect-square w-full bg-cover bg-center relative group"
                            style={{
                                backgroundImage: item.generatedImage
                                    ? `url(${item.generatedImage})`
                                    : item.originalImage
                                        ? `url(${item.originalImage})`
                                        : 'linear-gradient(to bottom right, #fbbf24, #f97316)',
                            }}
                        >
                            <button className="absolute top-2 right-2 bg-black/50 hover:bg-black/70 text-white p-2 rounded-full backdrop-blur-sm opacity-0 group-hover:opacity-100 transition-opacity">
                                <span className="material-symbols-outlined text-[16px]">edit</span>
                            </button>
                            <div className="absolute bottom-2 left-2 bg-black/60 backdrop-blur-md px-2 py-1 rounded-md flex items-center gap-1">
                                <span className="material-symbols-outlined text-white text-[12px]">auto_awesome</span>
                                <span className="text-[10px] text-white font-medium">AI Generated</span>
                            </div>
                        </div>

                        {/* Caption */}
                        <div className="p-4">
                            <div className="flex justify-between items-center mb-2">
                                <h3 className="font-bold text-sm text-text-main dark:text-white">
                                    {item.headline || item.originalTitle}
                                </h3>
                                <button className="text-primary hover:text-primary/80">
                                    <span className="material-symbols-outlined text-[16px]">refresh</span>
                                </button>
                            </div>
                            <p className="text-sm text-text-main dark:text-gray-300 leading-relaxed whitespace-pre-line">
                                {caption || 'Caption will be generated...'}
                            </p>
                        </div>
                    </div>
                </div>

                {/* Stats/Metadata */}
                <div className="grid grid-cols-2 gap-4 mb-6">
                    <div className="p-3 bg-background-light dark:bg-background-dark rounded-lg">
                        <span className="block text-[10px] text-text-muted uppercase mb-1">Character Count</span>
                        <span className="block text-sm font-bold text-text-main dark:text-white">
                            {caption?.length || 0} / 2200
                        </span>
                    </div>
                    <div className="p-3 bg-background-light dark:bg-background-dark rounded-lg">
                        <span className="block text-[10px] text-text-muted uppercase mb-1">Hashtags</span>
                        <span className="block text-sm font-bold text-text-main dark:text-white">
                            {(caption?.match(/#\w+/g) || []).length} / 30
                        </span>
                    </div>
                </div>
            </div>

            {/* Sticky Footer Actions */}
            {showActions && (
                <div className="p-6 border-t border-border-light dark:border-border-dark bg-surface-light dark:bg-surface-dark sticky bottom-0">
                    <button
                        onClick={() => onApprove?.(item)}
                        className="w-full bg-primary hover:bg-primary/90 text-primary-content font-bold py-3 rounded-lg shadow-lg shadow-primary/20 mb-3 flex items-center justify-center gap-2 transition-all"
                    >
                        <span className="material-symbols-outlined">check_circle</span>
                        Approve & Schedule
                    </button>
                    <div className="flex gap-3">
                        <button
                            onClick={() => onEdit?.(item)}
                            className="flex-1 bg-transparent border border-border-light dark:border-border-dark hover:bg-background-light dark:hover:bg-background-dark text-text-main dark:text-white font-medium py-2.5 rounded-lg flex items-center justify-center gap-2 transition-colors"
                        >
                            <span className="material-symbols-outlined text-[18px]">edit_note</span>
                            Edit
                        </button>
                        <button
                            onClick={() => onReject?.(item)}
                            className="flex-1 bg-transparent border border-red-200 dark:border-red-900/50 hover:bg-red-50 dark:hover:bg-red-900/20 text-red-600 dark:text-red-400 font-medium py-2.5 rounded-lg flex items-center justify-center gap-2 transition-colors"
                        >
                            <span className="material-symbols-outlined text-[18px]">delete</span>
                            Reject
                        </button>
                    </div>
                </div>
            )}
        </aside>
    );
}
